apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel-headless
  labels:
    app.bkraujo.io/name: redis
    app.bkraujo.io/instance: sentinel
    app.bkraujo.io/part-of: <aplicacao>
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: sentinel
      port: 5000
      protocol: TCP
      targetPort: sentinel
  selector:
    app.bkraujo.io/name: redis
    app.bkraujo.io/instance: sentinel
    app.bkraujo.io/part-of: <aplicacao>
